services:
  vault:
    image: hashicorp/vault:latest
    ports:
      - "127.0.0.1:8200:8200"
    env_file:
      - .env
    volumes:
      - ./volumes/vault/config:/vault/config
    entrypoint: vault server -config /vault/config/config.hcl
